# Generated by Django 4.2.8 on 2024-01-01 03:57

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="tags",
            field=models.ManyToManyField(to="core.tag"),
        ),
    ]
